Added methods to set default namespace (onprem only)
oracle/nosql-java-sdk pull request #40
Opened 2023-01-23 19:18 UTC by connelly38

Methods are hidden for now.
Requires onprem KV version 22.3, patch revision 24 or higher.

2023-01-23 20:06 UTC, cezarfx requested changes

2023-01-23 20:06 UTC, cezarfx commented on driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java
> +     * syntax) in requests and/or SQL statements overrides this default.
This is wrong, the default namespace is used when query doesn't explicitly specify a namespace, but one needs to be used.
For example "`select * from Customer`" with defaultNamespace set to "c1Ns" would resolve to: "`select * from  c1Ns:Customer`".
This means that the doc should say: "_Any non namespace qualified table name in requests and/or SQL statements would be resolved/qualified to the specified namespace._"

2023-01-23 20:06 UTC, cezarfx commented on driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java
> +     *
Same comment here.

2023-01-23 20:06 UTC, cezarfx commented on driver/src/main/java/oracle/nosql/driver/util/HttpConstants.java
> +    public static final String REQUEST_NAMESPACE_HEADER = "x-nosql-namespace";
Maybe use 'x-nosql-default-namespace' or 'x-nosql-default-ns' if first is too long.

2023-01-26 20:20 UTC, gmfeinberg commented on driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java
> +     * Onprem use only.
the other place(s) use "On-premise only" (i.e. not "onprem")

2023-01-26 20:22 UTC, gmfeinberg commented on driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java
> +     * Onprem use only.
"On-premise only"

2023-01-26 20:22 UTC, gmfeinberg commented on driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java
> +     * @hidden
Why is this (and corresponding get) hidden?

2023-01-26 20:25 UTC, gmfeinberg commented
Shouldn't there be per-request methods as well, similar to compartment?

2023-01-31 18:21 UTC, cezarfx commented on driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java
>      private String namespace;
Maybe renaming the property to defaultNamespace would be more self explanatory.

2023-01-31 19:13 UTC, connelly38 commented on driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java
>      private String namespace;
Good idea. Done.

2023-02-07 19:31 UTC, cezarfx commented on driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java
>      private String namespace;
Rename to defaultNamespace for clarity.

2023-02-07 19:39 UTC, connelly38 commented on driver/src/main/java/oracle/nosql/driver/NoSQLHandleConfig.java
>      private String namespace;
I did this already....

2023-02-07 20:33 UTC, cezarfx approved these changes
Looks good and per request defaultNamespace will be added in a different PR.

2023-02-07 22:33 UTC, merged